{% set name = "liteeth" %}
{% set version = "2024.08" %}
{% set sha256 = "c1c2baca29c3a617c68368c71329c6a562ddbaeaca7eb99b983d7894c10fdae8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/enjoy-digital/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation
  entry_points:
    - liteeth_gen = liteeth.gen:main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - litex >=2024.04
    - liteiclink >=2024.04
    - packaging
    - pyyaml

test:
  imports:
    - liteeth
  commands:
    - liteeth_gen --help

about:
  home: https://github.com/enjoy-digital/liteeth
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Small footprint and configurable Ethernet core
  description: Small footprint and configurable Ethernet core
  dev_url: https://github.com/enjoy-digital/liteeth

extra:
  recipe-maintainers:
    - enjoy-digital
    - timkpaine
