{% set name = "liteeth" %}
{% set version = "2022.12" %}
{% set sha256 = "43c72b88703c4173955d97d88bc647c345115005c4ca24d50c9039cbeac630e7" %}

package:
   name: {{ name|lower }}
   version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/enjoy-digital/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - patches/0001-add-manifest-uplift-setup.py-to-pass-twine-checks.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation
  entry_points:
    - liteeth_gen = liteeth.gen:main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - litex
    - liteiclink
    - pyyaml

test:
  imports:
    - liteeth
  commands:
    - liteeth_gen --help

about:
  home: https://github.com/enjoy-digital/liteeth
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Small footprint and configurable Ethernet core
  description: Small footprint and configurable Ethernet core
  dev_url: https://github.com/enjoy-digital/liteeth

extra:
  recipe-maintainers:
    - enjoy-digital
    - timkpaine
