{% set name = "liteeth" %}
{% set version = "2024.12" %}
{% set sha256 = "9b8b9430c3292535e7905ec9d54c82ad21c261bb52459785b864fef8c1c87f47" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/enjoy-digital/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps
  entry_points:
    - liteeth_gen = liteeth.gen:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - litex ~={{ version }}*
    - liteiclink ~={{ version }}*
    - packaging
    - pyyaml

test:
  imports:
    - liteeth
  requires:
    - python {{ python_min }}
  commands:
    - liteeth_gen --help

about:
  home: https://github.com/enjoy-digital/liteeth
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Small footprint and configurable Ethernet core
  description: Small footprint and configurable Ethernet core
  dev_url: https://github.com/enjoy-digital/liteeth

extra:
  recipe-maintainers:
    - enjoy-digital
    - timkpaine
